### ISSUE TITLE
Dependencies problem on NPM install

### ISSUE THREAD

**Issue by LouRaul** [learnwithjason/astro-frontend-masters#2]
Hi, I got this error while trying to install all the dependencies from the "start" brunch. any idea what could be wrong or how to fix it?

Switched to a new branch 'start'
rolo@Rauls-MacBook-Air astro-frontend-masters % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nanostores/solid@0.3.2
npm ERR! Found: nanostores@0.8.0
npm ERR! node_modules/nanostores
npm ERR!   nanostores@"^0.8.0" from the root project
npm ERR!   peer nanostores@"^0.8.0" from @nanostores/react@0.5.0
npm ERR!   node_modules/@nanostores/react
npm ERR!     @nanostores/react@"^0.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer nanostores@"^0.7.0" from @nanostores/solid@0.3.2
npm ERR! node_modules/@nanostores/solid
npm ERR!   @nanostores/solid@"^0.3.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: nanostores@0.7.4
npm ERR! node_modules/nanostores
npm ERR!   peer nanostores@"^0.7.0" from @nanostores/solid@0.3.2
npm ERR!   node_modules/@nanostores/solid
npm ERR!     @nanostores/solid@"^0.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by dtauer** [comment]
@LouRaul What version of Node are you using? We recommend Node 18.14.1 or higher. I just tested it with 18.17.1 and the installation worked.

**Comment by bonface221** [comment]
@LouRaul  try 
npm cache clean --force
npm install

if that does not work try shifting to yarn

**Comment by NickWoodward** [comment]
> @LouRaul What version of Node are you using? We recommend Node 18.14.1 or higher. I just tested it with 18.17.1 and the installation worked.

I've got the same issue on 18.17.1 unfortunately :/
@LouRaul - did you ever sort this?

*Edit: Uninstalling then reinstalling the packages worked

**Comment by vientang** [comment]
Hey guys, I ran into the same issue. Neither updating node version to 18.17.1 or npm cache clean --force worked but using yarn worked. 🤷‍♂️

**Comment by hvanlear** [comment]
Ran into the same issue with node v20.9.0. Worked with Yarn.

**Comment by dtauer** [comment]
Closing since the solution is to make sure you are using the recommended Node version: `Node 18.14.1`
